### ISSUE TITLE
Extension VS 2019 compatible

### ISSUE THREAD

**Issue by luislhg** [firesharkstudios/InheritDoc#10]
Awesome extension, could you please make the extension/vsix available for VS 2019?

**Comment by douglasg14b** [comment]
100% this!

Some cursory info here: https://devblogs.microsoft.com/visualstudio/how-to-upgrade-extensions-to-support-visual-studio-2019/

**Comment by Thieum** [comment]
I gave it a try in https://github.com/Thieum/InheritDoc/tree/vs2019-support

The manual mode works, but the build triggers don't seem to work anymore - I tried different things, like changing the DTE object to _DTE for the events, or updating the VS-related nuget packages with no success.

If anyone is more familiar than I am with VS SDK, any help woud be appreciated :)

**Comment by douglasg14b** [comment]
@firesharkstudios Why was the issue closed without comment? 

Was this resolved, will it not be considered?....etc

**Comment by firesharkstudios** [comment]
We've merged a pull request to implement support for VS 2019 extension
