### ISSUE TITLE
Tool exits with error

### ISSUE THREAD

**Issue by svenboulanger** [firesharkstudios/InheritDoc#5]
I would like to use this extension in combination with DocFx as indicated on the website.
I installed it as a Visual Studio Extension.

Whenever I run the tool (Tools > Run InheritDoc now) it immediately exits with the message:

```
Could not load file or assembly 'InheritDocLib, Version=2.0.0.0,
Culture=neutral, PublicKeyToken=3a819612142a34d3' or one of its
dependencies. (...)
```

Installing in other ways also failed in various ways.

Installing it for the project using NuGet installed a lot of unnecessary dependencies for one of my projects (NLog, Mono libraries, etc.). It also failed for a project targeting .NET Standard 2.0, so I tried to uninstall it, which failed on the message that "visual studio package with id ... does not exist" or something similar. I had to remove any references manually, and clean the whole solution.

Using the package manager seemed to install fine until I tried to run the command, telling me the command didn't exist.

**Comment by firesharkstudios** [comment]
Other than that, it works fine, right?  ;)

I'm a bit swamped at the moment but I'll try to get to it when I can.  Sure it can all be fixed.

**Comment by firesharkstudios** [comment]
I think most of the problems above were created when switching InheritDocLib to .NET Core.  I've made InheritDocLib a shared project and it's just getting compiled into the command line tool and the VSIX.

Yes, InheritDoc uses NLog and Mono.Cecil.  Perhaps using InheritDoc as a .NET Core Global Tool or using InheritDoc VSIX would solve this.

Everything work ok now?
